### PR TITLE
PFA_Analyzer

### PR DESCRIPTION
**Pull request by fraivone**
Code used to analyze GEM Common NTuples. 
Original repo --> https://github.com/fraivone/PFA_Analyzer

### CODE REVIEW

**Comment by jshlee** [comment]
@fraivone can you remove pyc files.

**Comment by jshlee** [comment]
* more general and descriptive names would be ideal, i.e PFA_Analyzer.py -> efficiencyAnalyzer.py
* for libs, myLIB -> lib and adding to PYTHONPATH is better for modules
* generally root files and other data shouldn't be included in repo, but since this is an example, move to 'example' folder

**Comment by fraivone** [comment]
@jshlee  updated the main branch on fraivone/pfa by:
* Removed pyc files
* Renamed to **./lib** folder
* renamed the PFA_Analyzer* to efficiencyAnalyzer*

**Comment by jshlee** [comment]
can you also change lib/forShawn.py to something more descriptive?
thanks

**Comment by fraivone** [comment]
ah thank you!That file is not needed for this analysis. 
Removed.

**Comment by jshlee** [comment]
can we get updates for the ntupler too

**Comment by fraivone** [comment]
The code we are using is here --> https://github.com/gmilella12/MuonDPGNTuples

I will issue a PR in the next days

**Pull request merged**
